In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ardhra\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ardhra\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ardhra\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\ardhra\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.8 MB 500.1 kB/s eta 0:00:18
   ---- ----------------------------------- 1.0/9.8 MB 500.1 kB/s eta 0:00:18
   ----- ---------------------------------- 1.3/9.8 MB 504.4 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.8 MB 504.4 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.8 MB 504.4 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.8 MB 469.2 kB/s eta 0:00:18
   ------- -------------------------------- 1.8/9.8 MB 534.1 kB/s eta 0:00:15
   ------- -------------------------------- 1.8/9.8 MB 534.1 kB/s eta 0:00:15
   ------- -------------------------------- 1.8/9.8 MB 534.1 kB/s eta 0:00:15
   -------- ------------------------------- 2.1/9.8 MB 517.0 kB/s eta 0:00:15
   --------- ------------------------------ 2.4/9.8 MB 542.4 kB/s eta 0:00:14
   ---------- ----------------------------- 2.6/9.8 MB 579.3 kB/s eta 0:00:13
   ----------- ---------------------------- 2.9/9.8 MB 618.6 kB/s eta 0:00:12
   ------------ --------------------------- 3.1/9.8 MB 655.1 kB/s eta 0:00:11
   ------------- -------------------------- 3.4/9.8 MB 678.8 kB/s eta 0:00:10
   ---------------- ----------------------- 3.9/9.8 MB 748.6 kB/s eta 0:00:08
   ----------------- ---------------------- 4.2/9.8 MB 780.2 kB/s eta 0:00:08
   ------------------ --------------------- 4.5/9.8 MB 784.9 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.8 MB 806.7 kB/s eta 0:00:07
   -------------------- ------------------- 5.0/9.8 MB 831.1 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.8 MB 835.1 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.8 MB 835.1 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.8 MB 831.8 kB/s eta 0:00:06
   ----------------------- ---------------- 5.8/9.8 MB 836.7 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.8 MB 836.7 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.8 MB 836.7 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.8 MB 836.7 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 780.5 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 780.5 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 780.5 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 780.5 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 733.1 kB/s eta 0:00:05
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.8 MB 388.8 kB/s eta 0:00:09
   --------------------------- ------------ 6.8/9.8 MB 9.9 kB/s eta 0:04:57
   --------------------------- ------------ 6.8/9.8 MB 9.9 kB/s eta 0:04:57
   --------------------------- ------------ 6.8/9.8 MB 9.9 kB/s eta 0:04:57
   --------------------------- ------------ 6.8/9.8 MB 9.9 kB/s eta 0:04:57
   --------------------------- ------------ 6.8/9.8 MB 9.9 kB/s eta 0:04:57
   --------------------------- ------------ 6.8/9.8 MB 9.9 kB/s eta 0:04:57
   ----------------------------- ---------- 7.1/9.8 MB 19.0 kB/s eta 0:02:22
   ----------------------------- ---------- 7.1/9.8 MB 19.0 kB/s eta 0:02:22
   ------------------------------ --------- 7.3/9.8 MB 27.9 kB/s eta 0:01:27
   ------------------------------ --------- 7.3/9.8 MB 27.9 kB/s eta 0:01:27
   ------------------------------- -------- 7.6/9.8 MB 36.7 kB/s eta 0:00:59
   -------------------------------- ------- 7.9/9.8 MB 45.4 kB/s eta 0:00:42
   -------------------------------- ------- 7.9/9.8 MB 45.4 kB/s eta 0:00:42
   -------------------------------- ------- 7.9/9.8 MB 45.4 kB/s eta 0:00:42
   --------------------------------- ------ 8.1/9.8 MB 53.4 kB/s eta 0:00:31
   --------------------------------- ------ 8.1/9.8 MB 53.4 kB/s eta 0:00:31
   --------------------------------- ------ 8.1/9.8 MB 53.4 kB/s eta 0:00:31
   ---------------------------------- ----- 8.4/9.8 MB 423.9 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.8 MB 423.9 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.8 MB 423.9 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.8 MB 423.9 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.8 MB 418.7 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.8 MB 418.7 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.8 MB 429.8 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.8 MB 429.8 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.8 MB 447.6 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.8 MB 447.6 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.8 MB 447.6 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 435.8 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 435.8 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 447.6 kB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 446.2 kB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
#creating data frames

In [5]:
# from dictionary
data={'Name':['Alice','Bob'],'Age':[25,30]}

In [6]:
df=pd.DataFrame(data)

In [7]:
#from list of lists

In [8]:
list=[['Alice',25],['Bob',30]]

In [9]:
df = pd.DataFrame(list, columns=['Name', 'Age'])

In [10]:
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
#inspecting data

In [16]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [17]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [18]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [20]:
#Selecting Data

In [21]:
#Column selection

In [22]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [24]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [25]:
#Row selection

In [26]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [33]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [34]:
#Filtering data

In [35]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [36]:
#Adding or removing columns

In [37]:
df['Gender']=['F','M']

In [38]:
df.drop('Age',axis=1,inplace=True)

In [39]:
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [40]:
#Handling missing data

In [41]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [42]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [44]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [48]:
df['Age']=[25,30]

In [46]:
#Grouping and aggregating

In [49]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [52]:
print(df)
df1=df

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [58]:
data={'NAME':['Afra','Gopika'],'GENDER':['F','F'],'AGE':[21,21]}
df2=pd.DataFrame(data)

In [51]:
#merge

In [56]:
pd.merge(df1,df2,on='Gender')

  Name_x Gender  Age_x  Name_y  Age_y
0  Alice      F     25    Afra     21
1  Alice      F     25  Gopika     21

In [59]:
df1.join(df2)

    Name Gender  Age    NAME GENDER  AGE
0  Alice      F   25    Afra      F   21
1    Bob      M   30  Gopika      F   21

In [60]:
# read csv

In [62]:
df=pd.read_csv("C:/Users/Ardhra/Downloads/50_Startups.csv")

In [63]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [64]:
#write csv
df.to_csv('output.csv', index=False)

In [65]:
df.sort_values('State')

    R&D Spend  Administration  Marketing Spend       State     Profit
49       0.00       116983.80         45173.06  California   14681.40
42   23640.93        96189.63        148001.11  California   71498.49
40   28754.33       118546.05        172795.67  California   78239.91
34   46426.07       157693.92        210797.67  California   96712.80
16   78013.11       121597.55        264346.06  California  126992.93
44   22177.74       154806.14         28334.72  California   65200.33
25   64664.71       139553.16        137962.62  California  107404.34
13   91992.39       135495.07        252664.93  California  134307.35
11  100671.96        91790.61        249744.55  California  144259.40
20   76253.86       113867.30        298664.47  California  118474.03
39   38558.51        82982.09        174999.30  California   81005.76
6   134615.46       147198.87        127716.82  California  156122.51
37   44069.95        51283.14        197029.42  California   89949.14
32   63408.86       129219.61         46085.25  California   97427.84
47       0.00       135426.92             0.00  California   42559.73
1   162597.70       151377.59        443898.53  California  191792.06
9   123334.88       108679.17        304981.62  California  149759.96
28   66051.52       182645.56        118148.20     Florida  103282.38
26   75328.87       144135.98        134050.07     Florida  105733.54
30   61994.48       115641.28         91131.24     Florida   99937.59
33   55493.95       103057.49        214634.81     Florida   96778.92
23   67532.53       105751.03        304768.73     Florida  108733.99
36   28663.76       127056.21        201126.82     Florida   90708.19
41   27892.92        84710.77        164470.71     Florida   77798.83
18   91749.16       114175.79        294919.57     Florida  124266.90
14  119943.24       156547.42        256512.92     Florida  132602.65
12   93863.75       127320.38        249839.44     Florida  141585.52
10  101913.08       110594.11        229160.95     Florida  146121.95
7   130298.13       145530.06        323876.68     Florida  155752.60
46    1315.46       115816.21        297114.46     Florida   49490.75
4   142107.34        91391.77        366168.42     Florida  166187.94
2   153441.51       101145.55        407934.54     Florida  191050.39
22   73994.56       122782.75        303319.26     Florida  110352.25
45    1000.23       124153.04          1903.93    New York   64926.08
38   20229.59        65947.93        185265.10    New York   81229.06
43   15505.73       127382.30         35534.17    New York   69758.98
0   165349.20       136897.80        471784.10    New York  192261.83
31   61136.38       152701.92         88218.23    New York   97483.56
29   65605.48       153032.06        107138.38    New York  101004.64
27   72107.60       127864.55        353183.81    New York  105008.31
48     542.05        51743.15             0.00    New York   35673.41
21   78389.47       153773.43        299737.29    New York  111313.02
19   86419.70       153514.11             0.00    New York  122776.86
17   94657.16       145077.58        282574.31    New York  125370.37
15  114523.61       122616.84        261776.23    New York  129917.04
8   120542.52       148718.95        311613.29    New York  152211.77
5   131876.90        99814.71        362861.36    New York  156991.12
3   144372.41       118671.85        383199.62    New York  182901.99
35   46014.02        85047.44        205517.64    New York   96479.51
24   77044.01        99281.34        140574.81    New York  108552.04

In [66]:
df['R&D Spend'].apply(lambda x: x + 1)

0     165350.20
1     162598.70
2     153442.51
3     144373.41
4     142108.34
5     131877.90
6     134616.46
7     130299.13
8     120543.52
9     123335.88
10    101914.08
11    100672.96
12     93864.75
13     91993.39
14    119944.24
15    114524.61
16     78014.11
17     94658.16
18     91750.16
19     86420.70
20     76254.86
21     78390.47
22     73995.56
23     67533.53
24     77045.01
25     64665.71
26     75329.87
27     72108.60
28     66052.52
29     65606.48
30     61995.48
31     61137.38
32     63409.86
33     55494.95
34     46427.07
35     46015.02
36     28664.76
37     44070.95
38     20230.59
39     38559.51
40     28755.33
41     27893.92
42     23641.93
43     15506.73
44     22178.74
45      1001.23
46      1316.46
47         1.00
48       543.05
49         1.00
Name: R&D Spend, dtype: float64

In [67]:
df['State'].unique()

<StringArray>
['New York', 'California', 'Florida']
Length: 3, dtype: str

In [68]:
df['R&D Spend'].value_counts()

R&D Spend
0.00         2
165349.20    1
162597.70    1
153441.51    1
144372.41    1
142107.34    1
131876.90    1
134615.46    1
130298.13    1
120542.52    1
123334.88    1
101913.08    1
100671.96    1
93863.75     1
91992.39     1
119943.24    1
114523.61    1
78013.11     1
94657.16     1
91749.16     1
86419.70     1
76253.86     1
78389.47     1
73994.56     1
67532.53     1
77044.01     1
64664.71     1
75328.87     1
72107.60     1
66051.52     1
65605.48     1
61994.48     1
61136.38     1
63408.86     1
55493.95     1
46426.07     1
46014.02     1
28663.76     1
44069.95     1
20229.59     1
38558.51     1
28754.33     1
27892.92     1
23640.93     1
15505.73     1
22177.74     1
1000.23      1
1315.46      1
542.05       1
Name: count, dtype: int64